apiVersion: v1
kind: ServiceAccount
metadata:
  name: microbin
  labels:
    app.kubernetes.io/name: microbin
---
apiVersion: v1
kind: Service
metadata:
  name: microbin
  labels:
    app.kubernetes.io/name: microbin
spec:
  ports:
  - name: https
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: microbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbin
  labels:
    app.kubernetes.io/name: microbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: microbin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microbin
    spec:
      serviceAccountName: microbin
      containers:
      - name: microbin
        image: microbin
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: TLS_ENABLED
          value: "true"
        - name: TLS_KEY_FILE
          value: "/var/tls/key.pem"
        - name: TLS_CERT_FILE
          value: "/var/tls/cert.pem"
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: certs
          mountPath: "/var/tls"
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: microbin-certs