apiVersion: v1
kind: ServiceAccount
metadata:
  name: microbin
---
apiVersion: v1
kind: Service
metadata:
  name: microbin
  labels:
    app: microbin
    service: microbin
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: microbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microbin
  template:
    metadata:
      labels:
        app: microbin
    spec:
      serviceAccountName: microbin
      containers:
      - name: microbin
        image: microbin:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName