apiVersion: v2
name: microbin
description: Accepts any HTTP request and returns the request's details including headers, parameters, query strings in JSON format

type: application

version: 1.0.1

appVersion: "v0.3.0"